//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.RecordsH = new HashSet<Record>();
            this.RecordsT = new HashSet<Record>();
        }
    
        public long RecordId { get; set; }
        public long FileId { get; set; }
        public int RecordTypeId { get; set; }
        public Nullable<long> HeaderRecordId { get; set; }
        public Nullable<long> TrailerRecordId { get; set; }
        public string Value { get; set; }
        public string PAN { get; set; }
        public string ExpiryDate { get; set; }
        public string RecordCount { get; set; }
    
        public virtual RecordType RecordType { get; set; }
        public virtual File File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> RecordsH { get; set; }
        public virtual Record Record1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> RecordsT { get; set; }
        public virtual Record Record2 { get; set; }
    }
}
